name: annya_nissaya
description: "Annya Nissaya"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.3+5

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  flutter_riverpod: ^2.3.7
  vs_scrollbar: ^1.0.0
  shared_preferences: ^2.0.5
  enum_to_string: ^2.0.1
  grouped_list: ^6.0.0
  scrollable_positioned_list: ^0.3.8
  path_provider: ^2.0.8
  path: ^1.8.0
  logger: ^2.0.2+1
  cupertino_icons: ^1.0.2
  flutter_widget_from_html_core: ^0.16.0
  sqflite: ^2.1.0
  sqflite_common_ffi: ^2.1.1+1
  # sqlite3_flutter_libs:
  just_pdf_viewer:
    git:
      url: https://github.com/pndaza/just_pdf_viewer
      ref: main
  app_links: ^7.0.0
  easy_debounce: ^2.0.3
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.1.4
  freezed: ^3.0.6
  msix: ^3.6.2
  build_runner:

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/database/annya_nsy.db
    - assets/books/cover/
    - assets/books/pdf/
    - assets/info.html

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"
